# Generated by Django 4.2.3 on 2023-07-14 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("board", "0002_blog_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 17, 58, 49, 665315, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
