# Generated by Django 4.2.3 on 2023-07-14 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_blog_created_at_blog_user_alter_blog_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 18, 3, 18, 475445, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
