# Generated by Django 4.2.3 on 2023-07-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_alter_blog_created_at_alter_blog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
