# Generated by Django 4.2.3 on 2023-07-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user"),
        ("board", "0005_alter_blog_created_at_alter_blog_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Account",),
    ]
